require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/wishlists', type: :request do
  # Wishlist. As you add validations to Wishlist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Wishlist.create! valid_attributes
      get wishlists_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      wishlist = Wishlist.create! valid_attributes
      get wishlist_url(wishlist)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      wishlist = Wishlist.create! valid_attributes
      get new_wishlist_url(wishlist)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      wishlist = Wishlist.create! valid_attributes
      get edit_wishlist_url(wishlist)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Wishlist' do
        expect do
          post wishlists_url, params: { wishlist: valid_attributes }
        end.to change(Wishlist, :count).by(1)
      end

      it 'redirects to the created wishlist' do
        post wishlists_url, params: { wishlist: valid_attributes }
        expect(response).to redirect_to(wishlist_url(Wishlist.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Wishlist' do
        expect do
          post wishlists_url, params: { wishlist: invalid_attributes }
        end.to change(Wishlist, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wishlists_url, params: { wishlist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested wishlist' do
        wishlist = Wishlist.create! valid_attributes
        patch wishlist_url(wishlist), params: { wishlist: new_attributes }
        wishlist.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the wishlist' do
        wishlist = Wishlist.create! valid_attributes
        patch wishlist_url(wishlist), params: { wishlist: new_attributes }
        wishlist.reload
        expect(response).to redirect_to(wishlist_url(wishlist))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wishlist = Wishlist.create! valid_attributes
        patch wishlist_url(wishlist), params: { wishlist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested wishlist' do
      wishlist = Wishlist.create! valid_attributes
      expect do
        delete wishlist_url(wishlist)
      end.to change(Wishlist, :count).by(-1)
    end

    it 'redirects to the wishlists list' do
      wishlist = Wishlist.create! valid_attributes
      delete wishlist_url(wishlist)
      expect(response).to redirect_to(wishlists_url)
    end
  end
end
